# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2a41806863511ad100a29fc412571e209486ab292dd8a3ededffa585625afef4b22b23e6faced8c726b8c08d89fde7a989396c6ecd5acb2ea368486dbe3321e1

test:
  secret_key_base: c3dc31b3cccb502550d1143dab7605f1fa8df887683708b8d3d25f3d549a2a619885f19ef4a30e39786576e7ff1f39da6d8d6d7e83b856efbb50796bb7afa3f5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
